spring:
  application:
    name: pull-push
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-bp1d3ra3968332d9ixo.mysql.rds.aliyuncs.com:3306/ptest?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: pmptest
    password: zkdj_yqgj2)!&
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: MEMORY
custom:
  custom-word:
    word:
      - 中印冲突,中印关系,中印*边境*冲突,中印*边境*对峙,中印*边界*冲突,中印*边界*对峙
      - 中美关系,拜登*对华态度,拜登*谴责中国,拜登*指责中国,中美双边关系
      - 后新冠,新冠疫苗*(普及+接种+研发+副作用+有效期+上市+有效+上新+试验+注册+抢跑+打不打+不建议打+不打+不良反应+不能打+获批+临床+研究+投入使用)
      - 美国*新冠,美国*肺炎,美国*疫情
  es:
    version: 5
    page-size: 500
    file-path: D:\\test
    analysis: http://127.0.0.1:8081
    es5: #es配置信息
      key: zkdj_yuQing
      host: http://116.62.153.127:8199/river
      #      host: http://116.62.153.127:8585
      app-id: 1231231
      full-query: /restserver/river/dataQuery
  quartz:
    corn: 0 0/1 * * * ?
    time: -1
