server:
  port: 8898
spring:
  application:
    name: pull-push
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/pull-push?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: MEMORY
custom:
  custom-word:
    word:
      - 新冠肺炎,肺炎疫情,新型冠状病毒,肺炎病例,肺炎确诊,新冠疫苗,新冠肺炎疫苗,建党百年
    author:
      - 吉林教育
      - 新疆教育厅
      - 江苏教育发布
      - 湘微教育
      - 海南省教育厅
      - 河北教育发布
      - 宁夏教育厅
      - 津门教育
      - 内蒙古教育发布
      - 辽宁省教育厅
    carrier:
  es:
    version: 5
    page-size: 500
    file-path: D:\test2
    read-model: File
    analysis: http://127.0.0.1:8081
    search-type: EXACT
    es5: #es配置信息
#      key: yq_test
      key: yq_zkdj
      host: http://river.junquan.com.cn
#      host: http://124.70.111.118:80
      app-id: 1231231
      full-query: /river/river/dataQuery
#      full-query: /restserver/river/dataQuery
  quartz:
#    每隔5秒执行一次：*/5 * * * * ?
#    每隔1分钟执行一次：0 */1 * * * ?
#    每天23点执行一次：0 0 23 * * ?
#    每天凌晨1点执行一次：0 0 1 * * ?
#    每月1号凌晨1点执行一次：0 0 1 1 * ?
#    每月最后一天23点执行一次：0 0 23 L * ?
#    每周星期天凌晨1点实行一次：0 0 1 ? * L
#    在26分、29分、33分执行一次：0 26,29,33 * * * ?
#    每天的0点、13点、18点、21点都执行一次：0 0 0,13,18,21 * * ?
    corn: 0 */1 * * * ?
#    YEAR, MONTH, DAY, HOUR, MINUTE, SECOND,
    time-type: MINUTE
    #    开始时间提前多少 需要跟corn对应
    time-range: -1
#    CUSTOM_AUTHOR(自定义作者) CUSTOM_WORD(自定义词) GATHER_WORD（词库中gather表）GATHER_AUTHOR（词库中author表） PUSH_ARTICLE 推送
    job-Type:
#      - CUSTOM_AUTHOR
#      - CUSTOM_WORD
      - GATHER_AUTHOR
    #    true 开启  false 关闭
    state: false
