version: '3'
services:
  pull-push:
    container_name: pull-push
    image: registry.cn-hangzhou.aliyuncs.com/zt_images/pull-push:latest
    ports:
      - '8080:8080'
    volumes:
      - /data/log:/log:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - pomp-pull.env
